apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-service
  labels:
    app: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sidecar-service
  template:
    metadata:
      labels:
        app: sidecar-service
    spec:
      containers:
        - name: sidecar-app
          image: sidecar:app
          ports:
            - containerPort: 8080
          env:
            - name: port
              value: "8080"

        - name: sidecar
          image: sidecar:sidecar
          ports:
            - containerPort: 80
          env:
            - name: port
              value: "80"
            - name: target
              value: "http://localhost:8080"

--- 

kind: Service
apiVersion: v1
metadata:
  name: sidecar-service
spec:
  selector:
    app: sidecar-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

