apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-service-two
  labels:
    app: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sidecar-service-two
  template:
    metadata:
      labels:
        app: sidecar-service-two
    spec:
      containers:
        - name: sidecar-app
          image: sidecar2-application:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6000
          env:
            - name: port
              value: "8080"

        - name: sidecar
          image: sidecar2-sidecar:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: TARGET
              value: "6000"
